### ISSUE TITLE
This source has memory leak.

### ISSUE THREAD

**Issue by medq2** [TheCruZ/EFI_Driver_Access#1]
I've tested several time, this source has memory leak.

when i looping readmemory, paged pool get real high.

**Comment by TheCruZ** [comment]
I have checked it and Windows system is allocating paged pool with the tag "Pp  ", I will try to check if we can free this pools

**Comment by Ignis34Rus** [comment]
Memory leak can be caused by usage of PsLookupProcessByProcessId without freeing object in Process parameter. In https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-pslookupprocessbyprocessid mentioned that 
> when a driver has completed using the Process parameter, the driver must call ObDereferenceObject to dereference the Process parameter received from the PsLookupProcessByProcessID routine.

**Comment by TheCruZ** [comment]
Yep I see that some time ago but I forgot to test it, maybe I test it in some time

**Comment by Ignis34Rus** [comment]
Seems like bug in windows kernel and it's not related to this source.
Tested on Windows 10 Pro Insider Preview (2004; Build 20226.1000) and Windows 10 Pro (2004; Build 19041.508)
Every call to NtSetSystemEnvironmentValueEx, NtQuerySystemEnvironmentValueEx or NtEnumerateSystemEnvironmentValuesEx will leak 32 bytes of memory in 'Pp  ' paged pool

**Comment by kenbun123** [comment]
Is there any way to free this pools?

**Comment by TheCruZ** [comment]
Only to close the issue as the leak don't come from this source, here you have more information about the memory leak https://github.com/TheCruZ/GetDeviceInterfacesMemoryLeak

**Comment by tesla7002** [comment]
What function can we use instead SetVariable?
