### ISSUE TITLE
Slow operations

### ISSUE THREAD

**Issue by v0idi** [TheCruZ/EFI_Driver_Access#2]
Hey thank you for this release
im having im problem with the efi driver rpms , its too slow compared to my other driver that uses ioctl 
is there anyway to accelerate it? 
Thank you

**Comment by TheCruZ** [comment]
Maybe you are doing to many operations simply try to read big amount of data for example when you are creating a hack for a game don't read entity position, name etc in different operations, read entire entity information and will work so smooth

Other option could be to use other function for the hook as probably make fewer operations
