### ISSUE TITLE
hard crash

### ISSUE THREAD

**Issue by Jillian51** [TheCruZ/EFI_Driver_Access#4]
hard crashing on 2 different computers
all running windows 10 2004, clean windows install 
cheat will run and crash in a few minutes
![minidump](https://user-images.githubusercontent.com/71793936/94070779-176b2700-fdf3-11ea-97f4-648ec42c8030.PNG)

the more i read - the faster it crashes
ram is good. only 10gb of 32 gb used

**Comment by TheCruZ** [comment]
I'm not able to find any issue, the code is running in a lot of computers without BSOD, you will need to check your client/ring3 application, also I try to call the driver extremely fast at the same time from different threads to see if that can cause the issue and the driver works fine
